""" 
Django settings for django_portfolio project.
 
Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import json
import os
import sys
mydir = 'etc'
myfile = 'config.json'
path = os.path.abspath(os.path.join(os.sep, mydir, myfile))
print(path)
with open(path) as config_file:
    config = json.load(config_file)
TESTING = 'test' in sys.argv
if TESTING:
    # Code specific to testing environment
    print("Running in test mode!")
else:
    print("Not running in test mode")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','stephen.photography', 'www.stephen.photography', 'code.stephen.photography']


# Application definition

INSTALLED_APPS = [
    'django_recaptcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'photo_app',
    'photo_blog',
    'storages',
    'ckeditor',
    'ckeditor_uploader',
    'phonenumber_field',
    'import_export',
    "django_check_seo",
    'cms',
    'menus',
    'treebeard',
    'code_portfolio',
    'markdown_deux',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':config['ENGINE'],
        'NAME':config['PORT_SITE'],
        'HOST':config['AWS_HOST'],
        'PORT':config['AWS_PORT'],
        'USER':config['AWS_USERNAME'],
        'PASSWORD':config['AWS_PASSWORD']
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_TZ = True

import os
PROJECT_DIR=os.path.dirname(__file__)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/



STATICFILES_FINDER = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

CKEDITOR_UPLOAD_PATH = '/photo_app/ckeditor_uploads/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS =True
EMAIL_HOST_PASSWORD = config.get('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER = config.get('EMAIL_HOST_USER')

AWS_QUERYSTRING_AUTH = False
DEFAULT_FILE_STORAGE = config['DEFAULT_FILE_STORAGE']
AWS_SECRET_ACCESS_KEY = config['AWS_SECRET_ACCESS_KEY']
AWS_ACCESS_KEY_ID =  config['AWS_ACCESS_KEY_ID']
AWS_STORAGE_BUCKET_NAME = config['AWS_STORAGE_BUCKET_NAME']
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERITY = True


RECAPTCHA_PUBLIC_KEY =  config['RECAPTCHA_PUBLIC_KEY']
RECAPTCHA_PRIVATE_KEY =  config['RECAPTCHA_PRIVATE_KEY']

INSTA_ACCESS_TOKEN = config['INSTA_ACCESS_TOKEN']

GOOGLE_API_KEY = config['GOOGLE_API_KEY']
GOOGLE_PLACE_ID = config['GOOGLE_PLACE_ID']

LOGIN_URL = '/login/'

BLOCKED_KEYWORDS = ['BTC', 'btc', 'crypto', 'seo', 'SEO', 'inappropriate', 'badword']

SITE_ID = 1

DATA_UPLOAD_MAX_NUMBER_FILES = 2000

SEO_SETTINGS = {
    'SITE_NAME': 'Stephen Lawson Photography',
    'DEFAULT_DESCRIPTION': 'Professional photography services in Richmond, Virginia',
    'DEFAULT_IMAGE': 'photo_app/img/header-banner.jpg',
    'TWITTER_HANDLE': '@StephenL_Photos',
}

# New SEO settings for the code portfolio
CODE_SEO_SETTINGS = {
    'SITE_NAME': 'Stephen Lawson - Developer Portfolio',
    'DEFAULT_DESCRIPTION': 'Python developer specializing in Django, automation, and data science',
    'DEFAULT_IMAGE': 'code_portfolio/img/header-banner.jpg',
    'TWITTER_HANDLE': '@StephenL_Photos',
}

# Required for sitemaps
SITE_ID = 1

def get_site_id(request):
    if request.get_host().startswith('code.'):
        return 2  # Code portfolio site
    return 1  # Default photography site

# Your site's domains
SITE_DOMAIN = 'stephen.photography'
CODE_SITE_DOMAIN = 'code.stephen.photography'



