# Generated by Django 5.0.1 on 2025-02-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
    ]
