# Generated by Django 5.0.1 on 2025-02-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_app", "0004_alter_cherryblossomsession_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cherryblossomsession",
            name="location",
            field=models.CharField(
                default="Brown's Island, Richmond, Virginia", max_length=200
            ),
        ),
    ]
