# Generated by Django 5.0.1 on 2025-02-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_app", "0005_alter_cherryblossomsession_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
