# Generated by Django 5.0.1 on 2025-02-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo_app", "0006_service_subtitle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="subtitle",
            new_name="extended_description",
        ),
    ]
