# Generated by Django 4.1.7 on 2023-11-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "photo_blog",
            "0003_tag_blogpost_active_blogpost_featured_blogpost_link_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
