# Generated by Django 4.1.7 on 2023-11-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo_blog", "0004_remove_blogpost_tags_delete_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="link",
        ),
    ]
