# Generated by Django 4.1.2 on 2023-11-29 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photo_blog", "0005_remove_blogpost_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="user_profile_photos/default_profile_photo.jpg",
                null=True,
                upload_to="user_profile_photos/",
            ),
        ),
    ]
