# Generated by Django 4.1.7 on 2023-11-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_blog", "0006_blogpost_author_blogpost_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                default="photo_app/img/insta-post-4.jpg",
                null=True,
                upload_to="blog_images/",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="photo_app/img/profile-photo.jpg",
                null=True,
                upload_to="user_profile_photos/",
            ),
        ),
    ]
