# Generated by Django 4.1.7 on 2023-11-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_blog", "0008_alter_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                default="photo_app/img/insta-post-4.jpg",
                null=True,
                upload_to="photo_app/img/media/",
            ),
        ),
    ]
