# Generated by Django 4.1.7 on 2023-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_blog", "0009_alter_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="photo_app/img/media/thumbnails/"
            ),
        ),
    ]
