# Generated by Django 5.0.1 on 2024-02-05 08:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo_blog", "0010_blogpost_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
