# Generated by Django 5.0.1 on 2025-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_blog", "0011_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Brief description for search engines. Keep under 160 characters for best results.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords for search engines.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional custom meta title. If not provided, the post title will be used.",
                max_length=200,
            ),
        ),
    ]
